INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE) VALUES('test1', 'test_desc1',100);
INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE) VALUES('test2', 'test_desc2',200);
INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE) VALUES('test3', 'test_desc3',300);

INSERT INTO MEMBER (USERNAME, PASSWORD) VALUES('user_id', '$2a$10$m/enYHaLsCwH2dKMUAtQp.ksGOA6lq7Fd2pnMb4L.yT4GyeAPRPyS');
